<a href="https://colab.research.google.com/github/patosaid/apuntes_python/blob/master/librerias_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [0]:
import numpy as np

In [0]:
mi_lista = [1,2,3]

In [0]:
type(np.array(mi_lista))

numpy.ndarray

In [0]:
arr = np.array(mi_lista)

In [0]:
arr

array([1, 2, 3])

Ahora se creará un array por medio de una funcion

In [0]:
np.arange(0,10) # va de 0 a 9
np.arange(0,11 , 2) # va de 0 a 10 de dos en dos

array([ 0,  2,  4,  6,  8, 10])

In [0]:
np.zeros(5) #esta funcion crea ceros

array([0., 0., 0., 0., 0.])

In [0]:
np.zeros((3,4)) # crea una matriz de ceros con dos () por tuplas

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
np.ones(3) # crea unos

array([1., 1., 1.])

In [0]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
np.linspace(1,10,3) # tres numeros entre 1 y 10
np.linspace(0,11,10000) #10000 numeros entre 0 y 11

array([0.00000000e+00, 1.10011001e-03, 2.20022002e-03, ...,
       1.09977998e+01, 1.09988999e+01, 1.10000000e+01])

In [0]:
np.random.randint(0,5) # un numero aleatorio entre 0 y 5 ( excluyente)

3

In [0]:
np.random.randint(0,5, (3,3))

array([[0, 2, 0],
       [1, 1, 2],
       [4, 1, 4]])

In [0]:
np.random.seed(101) # fijo la seed

np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [0]:
np.random.randint(0,100,10) # crea otros valores porq la seed no es la misma

array([76, 95, 87,  0, 73,  8, 62, 36, 83, 99])

In [0]:
arr = np.random.randint(0,100,10)

In [0]:
arr

array([71, 15, 44,  0, 12, 17, 75, 79, 97, 93])

In [0]:
arr.max() # el maximo de la variable arr

97

In [0]:
arr.min()

0

In [0]:
arr.argmax() # entrega el index del maximo

8

In [0]:
arr[arr.argmax()]

97

In [0]:
arr.reshape(2,5)  # transforma en filas 

array([[71, 15, 44,  0, 12],
       [17, 75, 79, 97, 93]])

In [0]:
mat = np.arange(0,100).reshape(10,10)

In [0]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [0]:
mat.size


100

In [0]:
# como agarrar un valor especifico con index
mat[0,1]

1

In [0]:
mat[4,3]

43

In [0]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [0]:
mat[5,]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [0]:
mat[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [0]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [0]:
#maskin?
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [0]:
filtro = mat>50
mat[filtro]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [0]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Pandas

Como leer csv

In [0]:
import pandas as pd

In [0]:
! pwd

/content


In [0]:
pd.read_csv(" ")

In [0]:
!pip install --upgrade -q gspread

In [0]:
from google.colab import auth
auth.authenticate_user()

import gspread
from oauth2client.client import GoogleCredentials

gc = gspread.authorize(GoogleCredentials.get_application_default())

worksheet = gc.open('Ejemplo_entradas_para_RNIN').sheet1

# get_all_values gives a list of rows.
rows = worksheet.get_all_values()
####################################################
#print(rows) para imprimir los datos###############

# Convert to a DataFrame and render.
import pandas as pd
###################################################
#pd.DataFrame.from_records(rows) para imprimir los datos en forma de tabla

In [0]:
rows

[['ID',
  'ALTURA_MEDIA',
  'DAP_MEDIO',
  'ALT_MEDIA_PODA',
  'DENSIDAD_PODADOS',
  'DENSIDAD',
  'PLI'],
 ['R1', '27,8', '31,6', '6,1', '360', '360', '1'],
 ['R2', '25,2', '28,2', '0', '0', '639', '0'],
 ['R3', '25,9', '24,9', '2,7', '1022', '1083', '0'],
 ['R4', '27,6', '27,9', '0', '0', '667', '0'],
 ['R5', '24,7', '24,6', '2,3', '975', '1075', '0'],
 ['R6', '24,5', '26,6', '0', '0', '693', '0'],
 ['R7', '23,2', '25,5', '0', '0', '684', '0'],
 ['R8', '31,8', '35,6', '5,6', '700', '700', '1'],
 ['R9', '32,2', '34,3', '5,5', '435', '442', '1']]

In [0]:
pd.DataFrame.from_records(rows)

0             1          2               3                 4         5    6
0  ID  ALTURA_MEDIA  DAP_MEDIO  ALT_MEDIA_PODA  DENSIDAD_PODADOS  DENSIDAD  PLI
1  R1          27,8       31,6             6,1               360       360    1
2  R2          25,2       28,2               0                 0       639    0
3  R3          25,9       24,9             2,7              1022      1083    0
4  R4          27,6       27,9               0                 0       667    0
5  R5          24,7       24,6             2,3               975      1075    0
6  R6          24,5       26,6               0                 0       693    0
7  R7          23,2       25,5               0                 0       684    0
8  R8          31,8       35,6             5,6               700       700    1
9  R9          32,2       34,3             5,5               435       442    1

In [117]:
type(rows)

list

Cómo pasar una lista a dataframa?   
https://thispointer.com/python-pandas-how-to-convert-lists-to-a-dataframe/




In [136]:
rows[0]
#rows[1:len(rows)+1]

['ID',
 'ALTURA_MEDIA',
 'DAP_MEDIO',
 'ALT_MEDIA_PODA',
 'DENSIDAD_PODADOS',
 'DENSIDAD',
 'PLI']

In [139]:
  df = pd.DataFrame(rows) # este queda la caga, en la siguienta linea lo arregle pero debe ser de otra manera creo
  df = pd.DataFrame(rows[1:len(rows)+1], columns = rows[0])
  df

ID ALTURA_MEDIA DAP_MEDIO ALT_MEDIA_PODA DENSIDAD_PODADOS DENSIDAD PLI
0  R1         27,8      31,6            6,1              360      360   1
1  R2         25,2      28,2              0                0      639   0
2  R3         25,9      24,9            2,7             1022     1083   0
3  R4         27,6      27,9              0                0      667   0
4  R5         24,7      24,6            2,3              975     1075   0
5  R6         24,5      26,6              0                0      693   0
6  R7         23,2      25,5              0                0      684   0
7  R8         31,8      35,6            5,6              700      700   1
8  R9         32,2      34,3            5,5              435      442   1

In [140]:
df["DAP_MEDIO"]

0    31,6
1    28,2
2    24,9
3    27,9
4    24,6
5    26,6
6    25,5
7    35,6
8    34,3
Name: DAP_MEDIO, dtype: object

In [141]:
df[["DAP_MEDIO"]]

DAP_MEDIO
0      31,6
1      28,2
2      24,9
3      27,9
4      24,6
5      26,6
6      25,5
7      35,6
8      34,3

In [142]:
df[["DAP_MEDIO","ALTURA_MEDIA"]]

DAP_MEDIO ALTURA_MEDIA
0      31,6         27,8
1      28,2         25,2
2      24,9         25,9
3      27,9         27,6
4      24,6         24,7
5      26,6         24,5
6      25,5         23,2
7      35,6         31,8
8      34,3         32,2

In [149]:
df[["ALTURA_MEDIA"]].max()

ALTURA_MEDIA    32,2
dtype: object

In [148]:
df.describe()

ID ALTURA_MEDIA DAP_MEDIO ALT_MEDIA_PODA DENSIDAD_PODADOS DENSIDAD PLI
count    9            9         9              9                9        9   9
unique   9            9         9              6                6        9   2
top     R7         27,8      26,6              0                0     1075   0
freq     1            1         1              4                4        1   6

In [152]:
df.as_matrix()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([['R1', '27,8', '31,6', '6,1', '360', '360', '1'],
       ['R2', '25,2', '28,2', '0', '0', '639', '0'],
       ['R3', '25,9', '24,9', '2,7', '1022', '1083', '0'],
       ['R4', '27,6', '27,9', '0', '0', '667', '0'],
       ['R5', '24,7', '24,6', '2,3', '975', '1075', '0'],
       ['R6', '24,5', '26,6', '0', '0', '693', '0'],
       ['R7', '23,2', '25,5', '0', '0', '684', '0'],
       ['R8', '31,8', '35,6', '5,6', '700', '700', '1'],
       ['R9', '32,2', '34,3', '5,5', '435', '442', '1']], dtype=object)

In [153]:
df.as_matrix

<bound method NDFrame.as_matrix of    ID ALTURA_MEDIA DAP_MEDIO ALT_MEDIA_PODA DENSIDAD_PODADOS DENSIDAD PLI
0  R1         27,8      31,6            6,1              360      360   1
1  R2         25,2      28,2              0                0      639   0
2  R3         25,9      24,9            2,7             1022     1083   0
3  R4         27,6      27,9              0                0      667   0
4  R5         24,7      24,6            2,3              975     1075   0
5  R6         24,5      26,6              0                0      693   0
6  R7         23,2      25,5              0                0      684   0
7  R8         31,8      35,6            5,6              700      700   1
8  R9         32,2      34,3            5,5              435      442   1>