<a href="https://colab.research.google.com/github/patosaid/apuntes_python/blob/master/librerias_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [0]:
import numpy as np

In [0]:
mi_lista = [1,2,3]

In [7]:
type(np.array(mi_lista))

numpy.ndarray

In [0]:
arr = np.array(mi_lista)

In [9]:
arr

array([1, 2, 3])

Ahora se creará un array por medio de una funcion

In [13]:
np.arange(0,10) # va de 0 a 9
np.arange(0,11 , 2) # va de 0 a 10 de dos en dos

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(5) #esta funcion crea ceros

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,4)) # crea una matriz de ceros con dos () por tuplas

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones(3) # crea unos

array([1., 1., 1.])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.linspace(1,10,3) # tres numeros entre 1 y 10
np.linspace(0,11,10000) #10000 numeros entre 0 y 11

array([0.00000000e+00, 1.10011001e-03, 2.20022002e-03, ...,
       1.09977998e+01, 1.09988999e+01, 1.10000000e+01])

In [47]:
np.random.randint(0,5) # un numero aleatorio entre 0 y 5 ( excluyente)

3

In [48]:
np.random.randint(0,5, (3,3))

array([[0, 2, 0],
       [1, 1, 2],
       [4, 1, 4]])

In [72]:
np.random.seed(101) # fijo la seed

np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [75]:
np.random.randint(0,100,10) # crea otros valores porq la seed no es la misma

array([76, 95, 87,  0, 73,  8, 62, 36, 83, 99])

In [0]:
arr = np.random.randint(0,100,10)

In [78]:
arr

array([71, 15, 44,  0, 12, 17, 75, 79, 97, 93])

In [79]:
arr.max() # el maximo de la variable arr

97

In [80]:
arr.min()

0

In [82]:
arr.argmax() # entrega el index del maximo

8

In [86]:
arr[arr.argmax()]

97

In [88]:
arr.reshape(2,5)  # transforma en filas 

array([[71, 15, 44,  0, 12],
       [17, 75, 79, 97, 93]])

In [0]:
mat = np.arange(0,100).reshape(10,10)

In [91]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [94]:
mat.size


100

In [95]:
# como agarrar un valor especifico con index
mat[0,1]

1

In [97]:
mat[4,3]

43

In [100]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [101]:
mat[5,]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [102]:
mat[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [106]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [107]:
#maskin?
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [108]:
filtro = mat>50
mat[filtro]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [109]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])